table_name: nifc_wildfire_locations
main_dttm_col: fire_discovery_time
description: Active wildfire incident locations from the NIFC WFIGS API
default_endpoint: null
offset: 0
cache_timeout: null
schema: public
sql: null
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
uuid: 76d55c98-dfec-4fb9-819e-05a673da945b
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  extra: null
  warning_text: null
- metric_name: avg_incident_size
  verbose_name: Avg Incident Size
  metric_type: avg
  expression: AVG(incident_size)
  description: null
  d3format: null
  extra: null
  warning_text: null
- metric_name: sum_estimated_cost
  verbose_name: Total Estimated Cost
  metric_type: sum
  expression: SUM(estimated_cost_to_date)
  description: null
  d3format: null
  extra: null
  warning_text: null
columns:
- column_name: fire_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: irwin_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: incident_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: incident_description
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: false
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: incident_size
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  groupby: false
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: percent_contained
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  groupby: false
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: discovery_acres
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  groupby: false
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: final_acres
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  groupby: false
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: estimated_cost_to_date
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  groupby: false
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: fire_cause
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: dispatch_center_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: origin_fips_code
  verbose_name: null
  is_dttm: false
  is_active: true
  type: CHAR(5)
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: origin_city_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: origin_state_code
  verbose_name: null
  is_dttm: false
  is_active: true
  type: CHAR(5)
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: origin_county_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: landowner_type
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: is_multijurisdictional
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: origin_coordinate
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: fire_discovery_time
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITH TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: containment_time
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITH TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: control_time
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITH TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: nifc_created_time
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITH TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
- column_name: nifc_modified_time
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITH TIME ZONE
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
version: 1.0.0
database_uuid: d601f9bf-b076-46fa-bd78-5aa1bd0b74b1
