slice_name: Storm Track Lines
description: NHC advisory forecast storm track lines connecting forecast points
certified_by: null
certification_details: null
viz_type: deck_geoset_map_layer
params:
  datasource: 30__table
  viz_type: deck_geoset_map_layer
  mapbox_style: mapbox://styles/acf-dart/cm8ov8yl4001401s365rs672z
  autozoom: true
  geojson: track_line
  row_limit: 1000
  geoJsonLayer: Polygon
  adhoc_filters: []
  minMaxZoomSlider:
  - 0
  - 22
  hoverDataColumns: []
  featureInfoColumns: []
  geojsonConfig: "{\n  \"globalColoring\": {\n    \"fillColor\": [77, 74, 57, 255],\n\
    \    \"fillPattern\": \"solid\",\n    \"lineStyle\": \"solid\",\n    \"strokeColor\"\
    : [77, 74, 57, 255],\n    \"strokeWidth\": 1\n  },\n  \"legend\": {\n    \"name\"\
    : \"Storms Tracks\",\n    \"title\": \"Storms Tracks\"\n  }\n}"
  schema_version: 2
  annotation_layers: []
cache_timeout: null
uuid: a1a862f1-2907-4ff5-a261-0d8e5199f63f
version: 1.0.0
dataset_uuid: 744ddd9c-c69c-4937-88ec-20e30bc098aa
