slice_name: Storm Track Points
description: NHC advisory forecast track points colored by maximum wind gusts
certified_by: null
certification_details: null
viz_type: deck_geoset_map_layer
params:
  datasource: 29__table
  viz_type: deck_geoset_map_layer
  mapbox_style: mapbox://styles/acf-dart/cm8ov8yl4001401s365rs672z
  autozoom: true
  geojson: forecast_point
  row_limit: 1000
  geoJsonLayer: Point
  clusterMaxZoom: 14
  clusterMinPoints: 2
  clusterRadius: 40
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: effective_timestamp
  minMaxZoomSlider:
  - 0
  - 22
  hoverDataColumns:
  - storm_name
  - formatted_timestamp
  - max_gust_mph
  - wind_speed_mph
  featureInfoColumns: []
  geojsonConfig: "{\n  \"colorByValue\": {\n    \"breakpoints\": [],\n    \"endColor\"\
    : [207, 30, 14, 255],\n    \"lowerBound\": 40,\n    \"startColor\": [222, 214,\
    \ 67, 255],\n    \"upperBound\": 157,\n    \"valueColumn\": \"max_gust_mph\"\n\
    \  },\n  \"globalColoring\": {\n    \"fillColor\": [40, 147, 179, 255],\n    \"\
    fillPattern\": \"solid\",\n    \"lineStyle\": \"solid\",\n    \"strokeColor\"\
    : [0, 0, 0, 255],\n    \"strokeWidth\": 2\n  },\n  \"legend\": {\n    \"title\"\
    : \"Maximum Wind Gusts (mph)\"\n  }\n}"
  schema_version: 2
  annotation_layers: []
cache_timeout: null
uuid: 6bf3672d-39e3-4170-b647-a46626cc899c
version: 1.0.0
dataset_uuid: 05f56898-3fc6-4bba-9c63-8dafb32343ea
