name: "DART Frontend Build"

on:
  push:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

env:
  TAG: dart-superset:GHA-${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker buildx build \
            -t $TAG \
            --target superset-node-ci \
            .

      - name: Run ESLint
        run: |
          docker run --rm $TAG bash -c "npm run eslint -- . --quiet"

      - name: Run TypeScript Check
        run: |
          docker run --rm $TAG bash -c "npm run type"

      - name: Build Plugins
        run: |
          docker run --rm $TAG bash -c "npm run plugins:build"
